name: Build application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
      - name: Build app and create zip file
        run : |  
        cd clients
        npm run build
        zip -j /home/naul2354/Desktop/todo-app/public/app.zip /home/naul2354/Desktop/todo-app/public/*
      - name: Publish zip file to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: app.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Login to DockerHub
  #       run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u naul2354 --password-stdin

  #     - name: Build and push Docker image
  #       run: |
  #         docker build -t naul2354/your-image-name:$(date '+%Y%m%d%H%M%S') .
  #         docker push naul2354/your-image-name:$(date '+%Y%m%d%H%M%S')
